### ISSUE TITLE
WSL and Windows Ollama

### ISSUE THREAD

**Issue by bamit99** [paulrobello/parllama#5]
I have installed Parllama on WSL2 and running Ollama on Windows. From within WSL, it is not able to connect with Ollama running on my PC IP, standard port. I am guessing because it is looking for Ollama on loopback within WSL. How can I point it to the regular IP of Ollama running on Windows? Cannot find any switch etc. to use for the same.

**Comment by paulrobello** [comment]
I will get this in tomorrow.
